export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";


export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_OUT = "SIGN_OUT"

export const SET_FOLLOW_STATUS = 'SET_PRIVATE'
export const SET_FOLLOW_STATUS_SUCCESS = 'SET_PRIVATE_SUCCESS'
export const SET_FOLLOW_STATUS_FAILURE = 'SET_PRIVATE_FAILURE'

