export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";


export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SIGN_OUT = "SIGN_OUT"

export const SET_FOLLOW_STATUS = 'SET_FOLLOW_STATUS'
export const SET_FOLLOW_STATUS_SUCCESS = 'SET_FOLLOW_STATUS_SUCCESS'
export const SET_FOLLOW_STATUS_FAILURE = 'SET_FOLLOW_STATUS_FAILURE'

export const EDIT_PROFILE = 'EDIT_PROFILE'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE'

export const UPDATE_AVATAR = 'UPDATE_AVATAR'
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS'
export const UPDATE_AVATAR_FAILURE = 'UPDATE_AVATAR_FAILURE'

export const DELETE_AVATAR = 'DELETE_AVATAR'
export const DELETE_AVATAR_SUCCESS = 'DELETE_AVATAR_SUCCESS'
export const DELETE_AVATAR_FAILURE = 'DELETE_AVATAR_FAILURE'
