

export const GET_LIST_FOLLOW_REQUEST = 'GET_LIST_FOLLOW_REQUEST'
export const GET_LIST_FOLLOW_REQUEST_SUCCESS = 'GET_LIST_FOLLOW_REQUEST_SUCSECC'

export const GET_LIST_FOLLOWER = 'GET_LIST_FOLLOWER'
export const GET_LIST_FOLLOWER_SUCCESS = 'GET_LIST_FOLLOWER_SUCCESS'

export const GET_LIST_FOLLOWING = 'GET_LIST_FOLLOWING'
export const GET_LIST_FOLLOWING_SUCCESS = 'GET_LIST_FOLLOWING_SUCCESS'

export const GET__FAILURE = 'GET__FAILURE'