

export const GET_LIST_REQUESTING_FOLLOW = 'GET_LIST_REQUESTING_FOLLOW'
export const GET_LIST_REQUESTING_FOLLOW_SUCCESS = 'GET_LIST_REQUESTING_FOLLOW_SUCSECC'
export const GET_LIST_REQUESTING_FOLLOW_FAILURE = 'GET_LIST_REQUESTING_FOLLOW_FAILURE'
