export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";



export const SEND_REQUEST_GET_ALL_USER = 'SEND_REQUEST_GET_ALL_USER';
export const SEND_REQUEST_GET_ALL_USER_SUCCESS = 'SEND_REQUEST_GET_ALL_USER_SUCCESS';
export const SEND_REQUEST_GET_ALL_USER_FAILURE = 'SEND_REQUEST_GET_ALL_USER_FAILURE';