export const ON_LOADING_AUTH = "ON_LOADING_AUTH";
export const ON_LOADING_SET_FOLLOW_STATUS = "ON_LOADING_SET_FOLLOW_STATUS";
export const ON_LOADING_FIND_USER = 'ON_LOADING_FIND_USER';
export const ON_LOADING_GET_LIST_POST = 'ON_LOADING_GET_LIST_POST'