export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

export const LOAD_MORE_POST = 'LOAD_MORE_POST';
export const LOAD_MORE_POST_SUCCESS = 'LOAD_MORE_POST_SUCCESS';


export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';


export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

export const COMMENT_POST = 'COMMENT_POST'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SECCESS'

export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST'
export const DELETE_COMMENT_POST_SUCCESS = 'DELETE_COMMENT_POST_SUCCESS'





export const POST_ERROR = 'POST_ERROR';