export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const SHOW_LOADING_GET_POST = 'SHOW_LOADING_GET_POST'
export const HIDE_LOADING_GET_POST = 'HIDE_LOADING_GET_POST'

export const LOAD_MORE_POST = 'LOAD_MORE_POST';
export const LOAD_MORE_POST_SUCCESS = 'LOAD_MORE_POST_SUCCESS';


export const ADD_POST = 'ADD_POST';
export const ON_ADDING_POSTS = 'ON_ADDING_POSTS'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const GET_LIST_POST_USER = 'GET_LIST_POST_USER'
export const GET_LIST_POST_USER_SUCCESS = 'GET_LIST_POST_USER_SUCCESS'

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

export const REACT_POST = 'REACT_POST';
export const REACT_POST_SUCCESS = 'REACT_POST_SUCCESS';



export const COMMENT_POST = 'COMMENT_POST'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS'

export const GET_LIST_COMMENT_POST = 'GET_LIST_COMMENT_POST'
export const GET_LIST_COMMENT_POST_SUCCESS = 'GET_LIST_COMMENT_POST_SUCCESS'


export const DELETE_COMMENT_POST = 'DELETE_COMMENT_POST'
export const DELETE_COMMENT_POST_SUCCESS = 'DELETE_COMMENT_POST_SUCCESS'

export const FIND_POST_BY_ID = 'FIND_POST_BY_ID'
export const FIND_POST_BY_ID_SUCCESS = 'FIND_POST_BY_ID_SUCCESS'




export const POST_ERROR = 'POST_ERROR';
