export const FIND_USER = 'FIND_USER'
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS'
export const FIND_USER_FAILURE = 'FIND_USER_FAILURE'

export const ADD_HISTORY_SEARCH = 'ADD_HISTORY_SEARCH'
export const DELETE_HISTORY_SEARCH = 'DELETE_HISTORY_SEARCH'

export const GET_PROFILE_USER_BY_ID = 'GET_PROFILE_USER_BY_ID'
export const GET_PROFILE_USER_BY_ID_SUCCESS = 'GET_PROFILE_USER_BY_ID_SUCCESS'
export const GET_PROFILE_USER_BY_ID_FAILURE = 'GET_PROFILE_USER_BY_ID_FAILURE'

export const POST_REQUEST_FOLLOW = 'POST_REQUEST_FOLLOW'
export const POST_REQUEST_FOLLOW_SUCCESS = 'POST_REQUEST_FOLLOW_SUCCESS'
export const POST_REQUEST_FOLLOW_FAILURE = 'POST_REQUEST_FOLLOW_FAILURE'

export const ACCEPT_REQUEST_FOLLOW = 'CONFIRM_REQUEST_FOLLOW'
export const ACCEPT_REQUEST_FOLLOW_SUCCESS = 'CONFIRM_REQUEST_FOLLOW_SUCCESS'
export const ACCEPT_REQUEST_FOLLOW_FAILURE = 'CONFIRM_REQUEST_FOLLOW_FAILURE'


export const REFUSE_REQUEST_FOLLOW = 'REFUSE_REQUEST_FOLLOW'
export const REFUSE_REQUEST_FOLLOW_SUCCESS = 'REFUSE_REQUEST_FOLLOW_SUCCESS'
export const REFUSE_REQUEST_FOLLOW_FAILURE = 'REFUSE_REQUEST_FOLLOW_FAILURE'