
export const FIND_USER = 'FIND_USER'
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS'
export const FIND_USER_FAILURE = 'FIND_USER_FAILURE'


export const ADD_HISTORY_SEARCH = 'ADD_HISTORY_SEARCH'
export const DELETE_HISTORY_SEARCH = 'DELETE_HISTORY_SEARCH'


export const GET_PROFILE_USER_BY_ID = 'GET_PROFILE_USER_BY_ID'
export const GET_PROFILE_USER_BY_ID_SUCCESS = 'GET_PROFILE_USER_BY_ID_SUCCESS'
export const GET_PROFILE_USER_BY_ID_FAILURE = 'GET_PROFILE_USER_BY_ID_FAILURE'