export const GET_LIST_CATEGORY_SONG = 'GET_LIST_CATEGORY_SONG'
export const GET_LIST_CATEGORY_SONG_SUCCESS = 'GET_LIST_CATEGORY_SONG_SUCCESS'

export const GET_LIST_SONG_BY_CATEGORY = 'GET_LIST_SONG_BY_CATEGORY' 
export const GET_LIST_SONG_BY_CATEGORY_SUCCESS = 'GET_LIST_SONG_BY_CATEGORY_SUCCESS'

export const FIND_SONG_BY_ID = 'FIND_SONG_BY_ID'
export const FIND_SONG_BY_ID_SUCCESS = 'FIND_SONG_BY_ID_SUCCESS'

export const LIKE_SONG = 'LIKE_SONG'
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS'

export const COMMENT_SONG = 'COMMENT_SONG'
export const COMMENT_SONG_SUCCESS = 'COMMENT_SONG_SUCCESS'

export const ADD_SONG = 'ADD_SONG'
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS'

export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS'

export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS'

export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST'
export const ADD_SONG_TO_PLAYLIST_SUCCESS = 'ADD_SONG_TO_PLAYLIST_SUCCESS'

export const DELETE_SONG_FROM_PLAYLIST = 'DELETE_SONG_FROM_PLAYLIST'
export const DELETE_SONG_FROM_PLAYLIST_SUCCESS = 'DELETE_SONG_FROM_PLAYLIST_SUCCESS'

export const FIND_PLAYLIST_BY_ID = 'FIND_PLAYLIST_BY_ID'
export const FIND_PLAYLIST_BY_ID_SUCCESS = 'FIND_PLAYLIST_BY_ID_SUCCESS'

export const FIND_PLAYLIST_BY_USERID = 'FIND_PLAYLIST_BY_USERID'
export const FIND_PLAYLIST_BY_USERID_SUCCESS = 'FIND_PLAYLIST_BY_USERID_SUCCESS'


export const ACTION_FAILURE = 'ACTION_FAILURE'