export const PLAYER_BAR = 'PLAYER_BAR'
export const SHOW_PLAYER_BAR = 'SHOW_PLAYER_BAR'
export const HIDE_PLAYER_BAR = 'HIDE_PLAYER_BAR'

export const PLAY_MUSIC = 'PLAY_MUSIC'
export const PAUSE_MUSIC = 'PAUSE_MUSIC'

export const ARRAY_SONGS = 'ARRAY_SONGS'
export const CHANGE_ARRAY_SONGS = 'CHANGE_ARRAY_SONGS'
export const ADD_SONG_TO_ARRAY = 'ADD_SONG_TO_ARRAY'
export const REMOVE_SONG_TO_ARRAY = 'REMOVE_SONG_TO_ARRAY'


export const GET_LIST_CATEGORY_SONG = 'GET_LIST_CATEGORY_SONG'
export const GET_LIST_CATEGORY_SONG_SUCCESS = 'GET_LIST_CATEGORY_SONG_SUCCESS'

export const GET_LIST_SONG_BY_CATEGORY = 'GET_LIST_SONG_BY_CATEGORY' 
export const GET_LIST_SONG_BY_CATEGORY_SUCCESS = 'GET_LIST_SONG_BY_CATEGORY_SUCCESS'

export const FIND_SONG_BY_ID = 'FIND_SONG_BY_ID'
export const FIND_SONG_BY_ID_SUCCESS = 'FIND_SONG_BY_ID_SUCCESS'

export const LIKE_SONG = 'LIKE_SONG'
export const LIKE_SONG_SUCCESS = 'LIKE_SONG_SUCCESS'

export const COMMENT_SONG = 'COMMENT_SONG'
export const COMMENT_SONG_SUCCESS = 'COMMENT_SONG_SUCCESS'

export const ADD_SONG = 'ADD_SONG'
export const ON_ADDING_SONG = 'ON_ADDING_SONG'
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS'
export const ADD_SONG_FAILURE = 'ADD_SONG_FAILURE'


export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS'

export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS'

export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST'
export const ADD_SONG_TO_PLAYLIST_SUCCESS = 'ADD_SONG_TO_PLAYLIST_SUCCESS'

export const DELETE_SONG_FROM_PLAYLIST = 'DELETE_SONG_FROM_PLAYLIST'
export const DELETE_SONG_FROM_PLAYLIST_SUCCESS = 'DELETE_SONG_FROM_PLAYLIST_SUCCESS'

export const GET_PLAYLIST_BY_LID = 'GET_PLAYLIST_BY_LID'
export const GET_PLAYLIST_BY_LID_SUCCESS = 'GET_PLAYLIST_BY_LID_SUCCESS'

export const GET_LIBRARY_OF_USER_BY_UID = 'GET_LIBRARY_OF_USER_BY_UID'
export const GET_LIBRARY_OF_USER_BY_UID_SUCCESS = 'GET_LIBRARY_OF_USER_BY_UID_SUCCESS'

export const SET_TAB_BAR_HEIGHT = 'SET_TAB_BAR_HEIGHT'

export const ACTION_FAILURE = 'ACTION_FAILURE'